giantswarm/capz-app-collection

flux-manifests/cluster-api.yaml
=> Update CAPI to latest so to match what we install during mc-bootstrap

flux-manifests/cluster-api-monitoring.yaml, flux-manifests/kustomization.yaml
=> enable CAPI monitoring app

flux-manifests/cluster-api-provider-azure.yaml
this is upgrading the capz-controller , same code but the version is the one built out of master when PR was merged
=> update cluster-api-provider-azure version

flux-manifests/kustomization.yaml, flux-manifests/kyverno-policies-connectivity.yaml
towards https://github.com/giantswarm/roadmap/issues/2021
=> add Kyverno connectivity policies to collection

flux-manifests/dns-operator-azure.yaml, flux-manifests/kustomization.yaml
=> add dns-operator-azure

flux-manifests/azure-ad-pod-identity-app.yaml
=> Match the same as the APP we push from mc-bootstrap

flux-manifests/app-operator.yaml, flux-manifests/athena.yaml, flux-manifests/cluster-api-monitoring.yaml, flux-manifests/dex-app.yaml, flux-manifests/dex-operator.yaml, flux-manifests/happa.yaml, flux-manifests/kustomization.yaml, flux-manifests/macropower-analytics-panel-server.yaml, flux-manifests/prometheus-meta-operator.yaml, flux-manifests/promxy-app.yaml
initial working capz version
update CAPZ-app-collection based on glippy management cluster with full opsctl integration
=> update CAPZ-app-collection based on glippy

flux-manifests/cluster-api-provider-azure.yaml
=> Upgrade cluster api provider azure to 1.8.0

flux-manifests/cluster-api-provider-azure.yaml
=> Run branch of cluster-api-provider-azure 1.8.0

flux-manifests/cluster-api-provider-azure.yaml
=> Test capz-controller 1.7.2

flux-manifests/cluster-api-provider-azure.yaml
=> Revert glippy capz controller to 1.7.0

flux-manifests/cluster-api-provider-azure.yaml
=> Test 1.6.3 on capz controller on glippy

flux-manifests/cluster-api-provider-azure.yaml
=> Test upstream 1.7.0 version of capz controller

flux-manifests/cluster-api-provider-azure.yaml
=> Upgrade capz controller to 1.8.1

flux-manifests/cluster-api-provider-azure.yaml
=> update capz to our own version

flux-manifests/cluster-api-provider-azure.yaml, flux-manifests/prometheus-meta-operator.yaml
=> Cuckoo auto branch

flux-manifests/dns-operator-azure.yaml
=> run dev-version of dns-operator for privatelink

flux-manifests/kyverno.yaml
=> Upgrade kyverno to latest stable

flux-manifests/azure-ad-pod-identity-app.yaml, flux-manifests/cluster-cleaner.yaml, flux-manifests/encryption-provider-operator.yaml, flux-manifests/etcd-backup-operator.yaml, flux-manifests/node-operator.yaml
Bump respective app versions to make them PSS compliant.
=> bump app versions for pss policies

flux-manifests/cluster-api-provider-azure.yaml
Towards https://github.com/giantswarm/roadmap/issues/2722
Fixed private links creation for private clusters deployed to pre-created VNets.
See https://github.com/giantswarm/roadmap/issues/2722.
No.
=> Update CAPZ app to v1.9.0-alpha.7

flux-manifests/ingress-nginx.yaml
Towards https://github.com/giantswarm/giantswarm/issues/28509.
Do not merge before https://github.com/giantswarm/config/pull/2113.
=> Collection: Add `ingress-nginx` v3.3.0.

flux-manifests/kustomization.yaml
Towards https://github.com/giantswarm/giantswarm/issues/28509.
=> Collection: Add `ingress-nginx.yaml` to `kustomization.yaml`.

flux-manifests/cluster-api.yaml
=> CAPI 1.5.7

flux-manifests/kustomization.yaml, flux-manifests/sloth-rules.yaml, flux-manifests/sloth.yaml
=> add missing sloth

flux-manifests/cluster-apps-operator.yaml, flux-manifests/prometheus-meta-operator.yaml
=> Update glean auto branch from main

flux-manifests/cluster-api-provider-azure.yaml
Use correct capz controller app version for glean
=> Use correct capz controller app version for glean

flux-manifests/cluster-api-provider-azure.yaml
This version fixes netpol issues.
=> Bump CAPZ from 1.9.0-alpha.8 to 1.9.0-alpha.9

flux-manifests/kustomization.yaml, flux-manifests/teleport-tbot.yaml
Towards  https://github.com/giantswarm/giantswarm/issues/30767
- Adds teleport-tbot app
=> Add teleport-tbot
